### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by missemily2022** [xorgram/xor#222]
![image](https://user-images.githubusercontent.com/97376138/180422944-3814815b-fb09-4a58-ad4a-85501a884eb2.png)

**Comment by roj1512** [comment]
This should be fixed. If not, reopen the issue. Thanks for reporting!

**Comment by missemily2022** [comment]
@roj1512 I tried deploying again.
And A new Error has appeared.
I have tagged you in #223
