### ISSUE TITLE
Built-in modules don't load if running from URL

### ISSUE THREAD

**Issue by missemily2022** [xorgram/xor#223]
![Heroku_Error](https://user-images.githubusercontent.com/97376138/180465860-752ea1e5-cbea-4879-ac0c-179efde40477.jpg)

**Comment by roj1512** [comment]
We’re working on fixing this. Thank you for reporting!

**Comment by missemily2022** [comment]
@roj1512 Okay!
I will be waiting for fixes from your Side...
