### ISSUE TITLE
External modules won't be able to import Xor classes after published to npm

### ISSUE THREAD

**Issue by roj1512** [xorgram/xor#51]
Title says it all.

**Comment by ArnabXD** [comment]
Can we use ["export"](https://nodejs.org/api/packages.html#package-entry-points) to trick the path ?

**Comment by roj1512** [comment]
Actually, I don't know. It seems a lil complicated. I'm thinking too...

**Comment by roj1512** [comment]
Seems I'm wrong, lmao. I think they can import from "@xorgram/xor" directly. Let's test it and close this if it is right.

**Comment by ArnabXD** [comment]
Yes , thinking the same , We might just need to update external plugins import pattern

**Comment by roj1512** [comment]
You saying this like if we already have 1K+ externals modules from the community 😂

**Comment by roj1512** [comment]
Importing `"@xorgram/xor/dist/handlers"` works. We can make it short too.

Closing this.

**Comment by ArnabXD** [comment]
> You saying this like if we already have 1K+ externals modules from the community 😂

😂
